### ISSUE TITLE
Better locking in iterators

### ISSUE THREAD

**Issue by joruof** [mertemba/structstore#10]
Currently the iterator returned by the ```__iter__``` method in the python bindings does only hold the ```read_lock``` during construction.
This could be modified so the iterator does hold the lock during its entire lifetime, which would prevent other processes from modifying the list during iteration.

**Comment by mertemba** [comment]
This should finally be fixed by 14a1fd5 ([as checked in this test](https://github.com/mertemba/structstore/blob/14a1fd5fdacf18e8a937323033c13451b49fd9b4/tests/test_lock_0.py#L35))
